name: gamehubtest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.6.0
  firebase_database: ^10.0.0
  firebase_storage: ^11.0.0
  provider: ^6.0.5
  uuid: ^4.2.0
  file_picker: ^5.2.5
  url_launcher: ^6.3.2
  flutter_downloader: ^1.11.4
  permission_handler: ^10.4.0
  path_provider: ^2.0.15
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
